server:
  port: 7001
#配置链路追踪地址
spring:
  main:
    allow-bean-definition-overriding: true
  zipkin:
    base-url: http://192.168.200.100:9411/
    sender:
      type: web
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 500
#        readTimeout: 5000