server:
  port: 8001
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
app:
  thread-pool:
    core: 4
    max: 8
    queue-size: 2000
    keep-alive-time: 300